# Generated by Django 5.1.3 on 2025-03-24 15:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.PositiveSmallIntegerField(choices=[(1, 'customer'), (2, 'admin'), (3, 'superadmin')], default=1)),
                ('password', models.CharField(max_length=300)),
                ('status', models.BooleanField(default=True)),
                ('login_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('otp_code', models.PositiveIntegerField(default=6036)),
                ('reset', models.BooleanField(default=False)),
                ('attempt', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_user', to='authentication.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
